version: '3.8'
name: solicitacao-email-mvp

networks:
  app-network:
    driver: bridge

services:
  backend:
    build: ./server
    container_name: backend
    networks:
      - app-network
    ports:
      - "5000:5000"
    volumes:
      - dbdata:/app/data
    environment:
      - PORT=5000

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - app-network
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5000

volumes:
  dbdata: {}
